name: Update Quarto Extensions

on:
  schedule:
    - cron: "0 6 1 * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2

      - uses: mcanouil/quarto-extensions-updater@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
